---
- name: Generate join command on Kubernetes master node
  hosts: kubernetes_master_nodes
  become: true
  tasks:
    - name: Create the join command and save to a file
      shell: kubeadm token create --print-join-command > /tmp/join.sh
      args:
        executable: /bin/bash
      run_once: true

- name: Prepare worker nodes for joining the Kubernetes cluster
  hosts: kubernetes_worker_nodes
  become: true
  vars_files:
    - env_variables

  tasks:
    - name: Ensure containerd is installed and updated
      yum:
        name: containerd.io
        state: latest
        
    - name: Remove custom containerd config to use default
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Restart and enable containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Add an entry to /etc/hosts for hostname resolution
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_host }} {{ inventory_hostname }}"
        state: present

    - name: Fetch the join script from the master node
      fetch:
        src: /tmp/join.sh
        dest: "/tmp/{{ inventory_hostname }}_join.sh"
        flat: yes
      delegate_to: "{{ groups['kubernetes_master_nodes'][0] }}"

    - name: Resetting kubeadm on worker nodes (if needed)
      command: kubeadm reset -f

    - name: Joining worker nodes to the Kubernetes cluster
      command: sh /tmp/join.sh
      register: join_result
      ignore_errors: true

    - name: Check join result
      fail:
        msg: "Failed to join the Kubernetes cluster"
      when: join_result.rc != 0
